---
- name: install docker dependencies
  ansible.builtin.package:
    name: "{{ docker_dependencies }}"
    state: present

- name: add apt signing key (debian)
  ansible.builtin.apt_key:
    url: "{{ docker_repo.gpg_url }}"
  become: true

- name: install official docker repositories for debian based
  ansible.builtin.template:
    src: etc/apt/sources.list.d/docker-ce.list.j2
    dest: /etc/apt/sources.list.d/docker-ce.list
    mode: 644
    owner: root
    group: root

- name: udpate cache
  ansible.builtin.apt:
    update_cache: yes
    # cache_valid_time: 3600 # Optional: Update cache if older than 1 hour (3600 seconds)
    force: true
