apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL for Let's Encrypt's production environment
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: jalinuxy@gmail.com
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key
      name: letsencrypt-prod-private-key
    solvers:
      # Use the HTTP-01 challenge provider with an NGINX Ingress
      - http01:
          ingress:
            class: nginx