- name: Install pip
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    # update_cache: true
    # loop:
    # - python3-apt
    # - python3-pip
  tags:
  - preparing

- name: Ensure the previous sourcelist is removed
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent
  tags:
  - prepare
  - remove_sourcelist
- name: Find everything inside source.list.d
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d/
    file_type: any
    recurse: yes
    hidden: yes
  register: found

- name: Remove found items
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ found.files }}"

- name: Copy the new sources.list file
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  tags:
  - prepare
  - copy_sourcelist
- name: Ensure the apt cache is updated
  ansible.builtin.apt:
    update_cache: yes
