apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  master.cnf: |
    [mysqld]
    log-bin
    server-id=1
    gtid-mode=ON
    enforce-gtid-consistency=ON
  slave.cnf: |
    [mysqld]
    super-read-only
    server-id=2
    gtid-mode=ON
    enforce-gtid-consistency=ON
