all:
  vars:
    #   ansible_user: debian
    ansible_port: 9510
  children:
    arvan:
      hosts:
        prom-prov:
          DOMAIN: prom.prov.lnx1.ir
        elk-prov:
          DOMAIN: elk.prov.lnx1.ir
