apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: final
data:
  master.cnf: |
    [mysqld]
    server_id=1
    log_bin=mysql-bin
    binlog_format=ROW
    default_authentication_plugin = mysql_native_password
    gtid_mode=ON
    enforce-gtid-consistency=ON
    local_infile=ON
    
    # ----- Tunings -----
    # innodb_buffer_pool_size       = 2600M     #--> we use this to enable cache for data 60-70% total mem and lower in OOM 
    # innodb_buffer_pool_instances  = 2         #--> we use to lower cachce connection for each instance
    # innodb_log_file_size          = 512M      #--> lower checkpoint but increase recovery time
    # innodb_flush_method           = O_DIRECT  #--> bypass os page cache
    # #innodb_flush_neighbors        = 0 
    # innodb_io_capacity            = 2000
    # innodb_io_capacity_max        = 4000
    # innodb_read_io_threads        = 4
    # innodb_write_io_threads       = 4
    # tmp_table_size                = 128M
    # max_heap_table_size           = 128M
    # table_open_cache              = 4000
    # table_open_cache_instances    = 8
    # thread_cache_size             = 64
    # max_connections               = 200
    # open_files_limit              = 65535
    # innodb_flush_log_at_trx_commit = 2
    # sync_binlog                   = 0 
  slave.cnf: |
    [mysqld]
    server_id=2
    log_bin=mysql-bin
    binlog_format=ROW
    gtid_mode=ON
    enforce_gtid_consistency=ON
    read_only=ON
    super_read_only=ON
    default_authentication_plugin=mysql_native_password
    # ----- Tuning ----- 
    # innodb_buffer_pool_size       = 2600M
    # innodb_buffer_pool_instances  = 2
    # innodb_log_file_size          = 512M
    # innodb_flush_method           = O_DIRECT
    # innodb_flush_neighbors        = 0
    # innodb_io_capacity            = 2000
    # innodb_io_capacity_max        = 4000
    # innodb_read_io_threads        = 4
    # innodb_write_io_threads       = 4
    # tmp_table_size                = 128M
    # max_heap_table_size           = 128M
    # table_open_cache              = 4000
    # table_open_cache_instances    = 8
    # thread_cache_size             = 64
    # max_connections               = 200
    # open_files_limit              = 65535
    local_infile                  = ON
