apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-metrics-ingress
  namespace: arvan-test
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: mysql-metrics-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: metrics.kube0.ir # <-- Your public domain
    http:
      paths:
      # Rule for the Master
      - path: /master(/|$)(.*)
        pathType: ImplementationSpecific # <-- CORRECTED
        backend:
          service:
            name: mysql-master-svc
            port:
              number: 9104
      # Rule for the Slave
      - path: /slave(/|$)(.*)
        pathType: ImplementationSpecific # <-- CORRECTED
        backend:
          service:
            name: mysql-slave-svc
            port:
              number: 9104
