- name: Get all data streams
  uri:
    url: "https://{{ SUBDOMAIN_ELASTIC }}.{{ DOMAIN }}/_data_stream"
    user: "{{ ELASTIC_USERNAME_MASKED }}"
    password: "{{ ELASTIC_PASSWORD_MASKED }}"
    method: GET
    headers:
      Content-Type: "application/json"
    validate_certs: false
  delegate_to: localhost
  register: data_streams_list
  failed_when: false
  tags:
  - template

- name: Loop over log types using include_tasks
  include_tasks: log_type.yml
  loop: "{{ log_types }}"
  loop_control:
    loop_var: log_type
  tags:
  - template
