# per_logtype.yml
- name: Set stream_exists for logs-{{ log_type }}
  set_fact:
    stream_exists: "{{ ('logs-' ~ log_type) in (data_streams_list.json.data_streams | map(attribute='name') | list) }}"

- name: Delete data stream logs-{{ log_type }} if exists
  uri:
    url: "https://{{ SUBDOMAIN_ELASTIC}}.{{ DOMAIN }}/_data_stream/logs-{{ log_type }}"
    user: "{{ ELASTIC_USERNAME_MASKED }}"
    password: "{{ ELASTIC_PASSWORD_MASKED }}"
    method: DELETE
    headers:
      Content-Type: "application/json"
      Authorization: "Basic {{ elastic_basic_auth }}"
    validate_certs: false
  when: stream_exists
  delegate_to: localhost
  failed_when: false

- name: Create index template for logs-{{ log_type }}
  uri:
    url: "https://{{ SUBDOMAIN_ELASTIC}}.{{ DOMAIN }}/_index_template/logs-{{ log_type }}-template"
    method: PUT
    headers:
      Content-Type: "application/json"
      Authorization: "Basic {{ elastic_basic_auth }}"
    validate_certs: false
    body_format: json
    body:
      index_patterns: [ "logs-{{ log_type }}-*" ]
      template:
        settings:
          index:
            number_of_shards: 1
            number_of_replicas: 1
            lifecycle:
              name: "{{ ilm_policies[log_type] }}"
              rollover_alias: "logs-{{ log_type }}"
        mappings:
          dynamic: true
          properties:
            "@timestamp":
              type: date
            message:
              type: text
      priority: 200
  register: create_template
  retries: 5
  delay: 10
  until: create_template.status == 200

- name: Create initial index logs-{{ log_type }}-000001
  uri:
    url: "https://{{ SUBDOMAIN_ELASTIC}}.{{ DOMAIN }}/logs-{{ log_type }}-000001"
    method: PUT
    headers:
      Content-Type: "application/json"
      Authorization: "Basic {{ elastic_basic_auth }}"
    validate_certs: false
    body_format: json
    body:
      aliases:
        logs-{{ log_type }}:
          is_write_index: true
  register: create_initial_index
  retries: 5
  delay: 10
  until: create_initial_index.status == 200
