---
# tasks file for observability

- name: Prepare ELK
  import_tasks: preparing.yml
  tags:
    - preparing_elk

- name: Deploy ELK
  import_tasks: deploy.yml
  tags:
    - delpoying_elk

- name: Health ELK
  import_tasks: health.yml

- name: Config ilm
  import_tasks: ilm.yml

- name: Config ilm
  import_tasks: test.yml
  tags:
    - config_ilm
