
- name: Copy file
  ansible.builtin.copy:
    src: pip.conf
    dest: /root/.config/pip/pip.conf
    mode: "0600"
  tags:
  - preparing_elk

- name: Install multi python packages
  ansible.builtin.pip:
    name:
    - docker
    - PyYAML==5.3.1
    - docker-compose
  tags:
  - preparing_elk
  - docker

- name: Create a docker network with name
  community.docker.docker_network:
    name: "{{ item }}"
    driver_options:
      com.docker.network.bridge.name: "{{ item }}"
  loop:
  - web-network
  - elk-network
  tags:
  - preparing_elk
  - docker

- name: Creates directory
  ansible.builtin.file:
    path: "{{ service_dir }}"
    state: directory
    mode: "0600"
  tags:
  - preparing_elk

- name: Create service subdirectories
  ansible.builtin.file:
    path: "{{ service_dir }}/{{ item }}"
    state: directory
    mode: "{{ service_dir_mode | default('0600') }}"
  loop: "{{ service_subdirs }}"
  tags: preparing_elk

- name: Template Elasticsearch configuration
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: "{{ service_dir }}/elasticsearch/elasticsearch.yml"
    mode: "{{ service_conf_mode }}"
  tags: preparing_elk

- name: Template Elasticsearch configuration
  ansible.builtin.template:
    src: health-check.sh.j2
    dest: "{{ service_dir }}/elasticsearch/health-check.sh"
    mode: "0600"
  tags: preparing_elk

- name: Template Kibana configuration
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: "{{ service_dir }}/kibana/kibana.yml"
    mode: "{{  service_conf_mode }}"
  tags: preparing_elk

- name: Template Logstash pipeline configuration
  ansible.builtin.template:
    src: logstash.yml.j2
    dest: "{{ service_dir }}/logstash/logstash.yml"
    mode: "{{ service_conf_mode }}"
  tags: preparing_elk

- name: Template Logstash pipeline configuration
  ansible.builtin.template:
    src: pipeline.conf.j2
    dest: "{{ service_dir }}/logstash/pipeline/pipeline.conf"
    mode: "{{ service_conf_mode }}"
  tags: preparing_elk

- name : Install rsyslog if not installed 
  apt:
    name: rsyslog
    state: present
  tags: preparing_elk
  
- name: Template Filebeat configuration
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: "{{ service_dir }}/filebeat-es/filebeat.yml"
    mode: "{{ service_conf_mode }}"
  tags: preparing_elk

- name: Template Filebeat configuration
  ansible.builtin.template:
    src: system.yml.j2
    dest: "{{ service_dir }}/filebeat-es/modules.d/system.yml"
    mode: "{{ service_conf_mode }}"
  tags: preparing_elk

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: compose.yml
    dest: "{{ service_dir }}/compose.yml"
    mode: "{{ service_conf_mode }}"
  tags:
  - preparing_elk

- name: Template a .env to path
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ service_dir }}/.env"
    mode: "{{ service_conf_mode }}"
  tags:
  - preparing_elk