apiVersion: v1
kind: Service
metadata:
  name: mysql-master-svc
spec:
  ports:
  - name: mysql
    port: 3306
  - name: mysql-exporter
    port: 9104 #>> use this port for mysql-metrics
    targetPort: 9104
  selector:
    app: mysql-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
<<<<<<< Updated upstream
  namespace: sre-challange
=======
  namespace: arvan-test
>>>>>>> Stashed changes
spec:
  selector:
    matchLabels:
      app: mysql-master
  serviceName: mysql-master-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-master
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9104'
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: ROOT_PASSWORD
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/conf.d
      - name: mysqld-exporter
        image: prom/mysqld-exporter:v0.14.0
        args:
        - "--collect.global_status"
        - "--collect.info_schema.innodb_metrics"
        - "--collect.auto_increment.columns"
        - "--collect.info_schema.processlist"
        - "--collect.binlog_size"
        - "--collect.info_schema.tablestats"
        - "--collect.global_variables"
        - "--collect.info_schema.query_response_time"
        - "--collect.info_schema.userstats"
        - "--collect.info_schema.tables"
        - "--collect.perf_schema.tablelocks"
        - "--collect.perf_schema.file_events"
        - "--collect.perf_schema.eventswaits"
        - "--collect.perf_schema.indexiowaits"
        - "--collect.perf_schema.tableiowaits"
        - "--collect.slave_status"
        ports:
        - containerPort: 9104
          name: exporter
        env:
        - name: DATA_SOURCE_NAME
          value: "root:$(MYSQL_ROOT_PASSWORD)@tcp(127.0.0.1:3306)/"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: ROOT_PASSWORD
      volumes:
      - name: config-volume
        configMap:
          name: mysql-config
          items:
          - key: master.cnf
            path: master.cnf
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
